### ISSUE TITLE
Filter language, filter language, filter language.

### ISSUE THREAD

**Issue by Tantusar** [demipixel/TWOWDiscordBot#15]

**Comment by demipixel** [comment]
Why, won't it just be voted down?

**Comment by Tantusar** [comment]
It's still a family-friendly server, and it still shows up.

**Comment by demipixel** [comment]
Has it been an issue?

**Comment by Tantusar** [comment]
Yes, and unless we delete the TWOWBot results message, we can't do anything about it. I think the response might have even won, so there goes the downvote theory.

**Comment by demipixel** [comment]
I haven't seen anybody complain and I rarely seen swearing...

**Comment by Tantusar** [comment]
![image](https://cloud.githubusercontent.com/assets/5593775/15761377/2bf03722-295b-11e6-90e5-d204bb1acc52.png)
Just because you rarely see it, doesn't mean it's not there.

**Comment by demipixel** [comment]
Okay, although my point still stands.

**Comment by Tantusar** [comment]
Mine is still just as valid. We're trying to keep this place clean.
