### ISSUE TITLE
I understand partial voting now.

### ISSUE THREAD

**Issue by Tantusar** [demipixel/TWOWDiscordBot#16]
You take the omitted letters and spread any remaining percentage points evenly.

For example, the eight player percentages are 7/7, 6/7, ..., 1/7, 0/7. So if I only vote for three (7/7, 6/7, 5/7) the remaining responses get the average of the remaining percentages. ((4/7+3/7+2/7+1/7+0/7)/5=10/7/5=10/5/7=2/7)

**Comment by demipixel** [comment]
Except you have to vote for all of them.

**Comment by Tantusar** [comment]
Well, in the bot implementation, sure.

**Comment by demipixel** [comment]
Okay, this isn't an issue, though :p
